# Daily Challenge: Data Handling and Analysis in Python

In [25]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.manifold import TSNE

In [2]:
df = pd.read_csv('datascience_salaries.csv')

In [3]:
df.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

In [7]:
# data normalization with min-max scaler

scaler = MinMaxScaler()
df['salary'] = scaler.fit_transform(df[['salary']])

In [8]:
df.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,0.601010
1,2,Data scientist,Full Time,Senior,Boston,USD,0.454545
2,3,Data scientist,Full Time,Senior,London,USD,0.191919
3,4,Data scientist,Full Time,Senior,Boston,USD,0.454545
4,5,Data scientist,Full Time,Senior,New York City,USD,0.601010

In [17]:
df['job_title'].value_counts()

job_title
Data scientist      394
Data analyst        368
Machine learning    289
Big data            101
ML Ops               19
Name: count, dtype: int64

In [21]:
df = df.drop(columns=["Unnamed: 0"])

In [22]:
df.head()

,job_title,job_type,experience_level,location,salary_currency,salary,job_title_enc
0,Data scientist,Full Time,Senior,New York City,USD,0.601010,2
1,Data scientist,Full Time,Senior,Boston,USD,0.454545,2
2,Data scientist,Full Time,Senior,London,USD,0.191919,2
3,Data scientist,Full Time,Senior,Boston,USD,0.454545,2
4,Data scientist,Full Time,Senior,New York City,USD,0.601010,2

In [23]:
X = df.drop(columns=["salary"])

In [24]:
import pandas as pd

X_encoded = pd.get_dummies(X)

In [26]:
X_encoded.head()

,job_title_enc,job_title_Big data,job_title_Data analyst,job_title_Data scientist,job_title_ML Ops,job_title_Machine learning,job_type_Full Time,job_type_Internship,experience_level_Entry,experience_level_Executive,...,location_Wilmington,location_Work from Home,location_Wrocław,location_Zurich,location_tel aviv,location_České Budějovice,location_İstanbul,salary_currency_EUR,salary_currency_GBP,salary_currency_USD
0,2,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,2,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,2,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_tsne_scaled = scaler.fit_transform(X_tsne)

In [ ]:
# dimensionality reduction with t-SNE

tsne = TSNE(
    n_components=2,
    perplexity=30,
    learning_rate=200,
    random_state=42
)

X_tsne = tsne.fit_transform(X_tsne_scaled)

In [33]:
salary_by_exp = df.groupby('experience_level')['salary'].agg(['mean', 'median', 'count'])
print(salary_by_exp)

                      mean    median  count
experience_level
Entry             0.030864  0.000000    126
Executive         0.232712  0.080808     13
Mid               0.110035  0.106061    305
Senior            0.227717  0.191919    727